#!/usr/bin/env python3
"""build-gradient-lighting.py — generate
ha-config/packages/living_lights_gradient.yaml (Phase 3 gradient lighting,
sofa zone).

Reads the hand-drawn footprints from spatial_model.json, computes each sofa
light's footprint-polygon centroid (the AR-3 separation check runs here),
and bakes them into a generated HA package:

  - input_number helpers for the live-tunable lambda / floor,
  - an MQTT sensor for the person's normalised position on the living_room
    camera (box bottom-centre = foot position),
  - a per-light gradient template sensor (the Gaussian falloff, baked
    centroids),
  - the gradient actuator automation (shadow-gated, additive — it layers
    per-light brightness over the existing sofa pilot's uniform output),
  - a per-light gradient-decision logger.

ADDITIVE: this does not touch build-living-lights-actuators.py or the 9
existing pilot YAMLs. Everything is gated by the existing default-OFF
living_lights_enabled + default-ON living_lights_shadow, so nothing
actuates until explicitly enabled.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gradient_lighting as GL                              # noqa: E402

REPO = Path(__file__).resolve().parent.parent
SPATIAL = REPO / "ha-config" / "spatial_model.json"
OUT = REPO / "ha-config" / "packages" / "living_lights_gradient.yaml"
CAMERA = "living_room"
# The 4 dimmable sofa lights (the 2 ambient switches have no brightness and
# keep their existing on/off behaviour — AR-10).
SOFA_LIGHTS = ["light.front_left", "light.front_right",
               "light.rear_left", "light.rear_right"]
E = "2.718281828"     # e, as a literal — no dependency on an HA `e` constant

# The YAML body. Jinja ({{ }}, {% %}) is literal here; only @@TOKEN@@
# placeholders are substituted, so there is no brace-escaping to get wrong.
_TEMPLATE = """\
# living_lights_gradient.yaml — GENERATED by tools/build-gradient-lighting.py
#
# Phase 3 gradient lighting for the "sofa" zone (camera=living_room). As the
# person moves on the sofa, the near light stays bright and the far lights
# dim — per-light brightness from each light's hand-drawn footprint centroid
# (baked below) and the person's live position.
#
# ADDITIVE — layered over the existing sofa pilot, touches no other file.
# INERT until all of:
#   input_boolean.living_lights_enabled = on
#   input_boolean.living_lights_shadow  = off
#   input_boolean.living_lights_zone_sofa_enabled = on
#
# Baked footprint centroids (normalised [0,1], from spatial_model.json):
@@CENTROID_COMMENT@@
#
# Rollback: delete this file + reload HA.

input_number:
  living_lights_gradient_lambda:
    name: Living Lights gradient lambda
    icon: mdi:blur
    min: 0.1
    max: 1.5
    step: 0.05
    initial: 0.6
  living_lights_gradient_floor:
    name: Living Lights gradient floor
    icon: mdi:arrow-collapse-down
    min: 0.1
    max: 1.0
    step: 0.05
    initial: 0.4

# Layer 3 gate — the gradient stays OFF until this is explicitly turned on,
# so activating Living Lights does not also activate the (not yet
# shadow-reviewed) sofa gradient. Default-off.
input_boolean:
  living_lights_gradient_enabled:
    name: "Living Lights — gradient enabled (Layer 3)"
    icon: mdi:gradient-vertical

mqtt:
  sensor:
    # Person foot-position on the living_room camera, normalised [0,1].
    # Frigate box is [x_min, y_min, x_max, y_max] in detect pixels
    # (@@DW@@x@@DH@@); foot = bottom-centre = ((x_min+x_max)/2, y_max).
    - name: "Living Room Person Position"
      unique_id: living_room_person_position
      state_topic: "frigate/events"
      value_template: "{% set a = value_json.after if value_json is mapping and 'after' in value_json else {} %}{% if a.get('camera') == 'living_room' and a.get('label') == 'person' and a.get('box') %}seen{% else %}{{ states('sensor.living_room_person_position') }}{% endif %}"
      json_attributes_topic: "frigate/events"
      json_attributes_template: "{% set a = value_json.after if value_json is mapping and 'after' in value_json else {} %}{% set b = a.get('box') %}{% if a.get('camera') == 'living_room' and a.get('label') == 'person' and b and b | length >= 4 %}{{ {'x': (((b[0] + b[2]) / 2.0) / @@DW@@) | round(4), 'y': ((b[3] | float) / @@DH@@) | round(4), 'seen': now().timestamp() | int} | tojson }}{% else %}{{ {'x': state_attr('sensor.living_room_person_position', 'x'), 'y': state_attr('sensor.living_room_person_position', 'y'), 'seen': state_attr('sensor.living_room_person_position', 'seen')} | tojson }}{% endif %}"

template:
  # Per-light gradient brightness. Recomputes on a position move, a
  # classifier-brightness change, or a lambda/floor tweak. Position unknown
  # or != 1 person in the room -> uniform (every light at the base pct, i.e.
  # exactly today's behaviour).
  - trigger:
      - trigger: state
        entity_id:
          - sensor.living_room_person_position
          - sensor.living_room_sofa_lighting_state
          - input_number.living_lights_gradient_lambda
          - input_number.living_lights_gradient_floor
      - trigger: homeassistant
        event: start
    action:
      - variables:
          px: "{{ state_attr('sensor.living_room_person_position', 'x') | float(-1) }}"
          py: "{{ state_attr('sensor.living_room_person_position', 'y') | float(-1) }}"
          base: "{{ state_attr('sensor.living_room_sofa_lighting_state', 'predicted_brightness_pct') | int(0) }}"
          lam: "{{ states('input_number.living_lights_gradient_lambda') | float(0.6) }}"
          flr: "{{ states('input_number.living_lights_gradient_floor') | float(0.4) }}"
          people: "{{ states('sensor.living_room_person_count') | int(0) }}"
          uniform: "{{ px < 0 or py < 0 or people != 1 }}"
@@RAW_VARS@@
          mx: "{{ [@@RAW_LIST@@] | max }}"
@@PCT_VARS@@
    sensor:
      - name: "Living Room Sofa Gradient"
        unique_id: living_room_sofa_gradient
        state: "{{ 'uniform' if uniform else 'gradient' }}"
        attributes:
@@ATTRIBUTES@@
          base_pct: "{{ base }}"
          person_x: "{{ px }}"
          person_y: "{{ py }}"

automation:
  # Gradient actuator — layers per-light brightness over the sofa pilot.
  # Shadow-gated; a 6 s rate-limit bounds Hue-bridge command volume (AR-2).
  - alias: "Living Lights - sofa gradient actuator"
    id: living_lights_gradient_sofa
    mode: queued
    max: 10
    triggers:
      - trigger: state
        entity_id: sensor.living_room_sofa_gradient
      # Periodic re-evaluation so manual-cooldown expiry isn't gated on a
      # gradient sensor state change (e.g., when the user is stationary).
      - trigger: time_pattern
        minutes: "/5"
    conditions:
      - condition: state
        entity_id: input_boolean.living_lights_enabled
        state: "on"
      - condition: state
        entity_id: input_boolean.living_lights_shadow
        state: "off"
      - condition: state
        entity_id: input_boolean.living_lights_zone_sofa_enabled
        state: "on"
      - condition: state
        entity_id: input_boolean.living_lights_gradient_enabled
        state: "on"
      - condition: state
        entity_id: sensor.living_room_sofa_lighting_state
        state:
          - present
          - pass_through
      # Manual-touch cooldown gate (R5-aligned, vacant-15-min semantics). Reads
      # input_datetime directly. State-bypass + asleep-bypass + sentinel-aware
      # — matches the pilot's cooldown gate exactly.
      - condition: template
        value_template: >-
          {% set state = states('sensor.living_room_sofa_lighting_state') %}
          {% set asleep = is_state('input_boolean.living_lights_asleep', 'on') %}
          {% if state not in ['vacant', 'present', 'pass_through'] or asleep %}true
          {% else %}
            {% set lm = states('input_datetime.living_lights_zone_sofa_last_manual_at') %}
            {% if not lm or lm in ['unknown', 'unavailable', 'none', ''] %}true
            {% else %}
              {% set manual_dt = as_datetime(lm | string) %}
              {% if manual_dt.year < 2000 %}true
              {% else %}
                {% set stable_obj = states.binary_sensor.living_room_sofa_person_occupancy_stable %}
                {% if stable_obj is none %}true
                {% elif stable_obj.state == 'on' %}false
                {% else %}
                  {% set leave_time = stable_obj.last_changed %}
                  {{ (now() - ([manual_dt, leave_time] | max)).total_seconds() > 900 }}
                {% endif %}
              {% endif %}
            {% endif %}
          {% endif %}
      - condition: template
        value_template: >-
          {% set lt = state_attr(this.entity_id, 'last_triggered') %}
          {% if lt %}{{ (now() - lt).total_seconds() > 6 }}{% else %}true{% endif %}
    actions:
      - variables:
          grad_ct: "{{ state_attr('sensor.living_room_sofa_lighting_state', 'predicted_color_temp_kelvin') | int(2700) }}"
@@ACTUATOR_ACTIONS@@
  # Per-light gradient-decision logger — shadow-mode visibility. Reuses the
  # shell_command from living_lights_shadow.yaml.
  - alias: "Living Lights - log sofa gradient decisions"
    id: living_lights_gradient_log_sofa
    mode: parallel
    max: 20
    triggers:
      - trigger: state
        entity_id: sensor.living_room_sofa_gradient
    conditions: []
    actions:
      - variables:
          json_payload: >-
            {{ {'ts': now().isoformat(), 'kind': 'gradient_decision', 'zone': 'sofa', 'state': states('sensor.living_room_sofa_gradient'), 'lights': @@LIGHTS_DICT@@, 'shadow_mode': is_state('input_boolean.living_lights_shadow', 'on')} | tojson }}
      - action: shell_command.living_lights_append_log
        data:
          payload: "{{ json_payload | base64_encode }}"
"""


def slug(eid):
    return eid.split(".", 1)[1]


def load_centroids():
    model = json.loads(SPATIAL.read_text(encoding="utf-8"))
    lights = model.get("lights", {})
    cam = (model.get("cameras", {}) or {}).get(CAMERA, {})
    dw = cam.get("detect_w", 1280)
    dh = cam.get("detect_h", 720)
    cents = {}
    for eid in SOFA_LIGHTS:
        rec = lights.get(eid) or {}
        poly = (rec.get("footprint_polygon") or {}).get(CAMERA)
        c = GL.polygon_centroid(poly) if poly else None
        if c is None:
            raise SystemExit(
                f"ERROR: {eid} has no {CAMERA} footprint — draw it in "
                f"/spatial first, then re-run.")
        cents[eid] = c
    return cents, dw, dh


def build_yaml(cents, dw, dh):
    raw_vars = []
    pct_vars = []
    attributes = []
    actuator = []
    for eid in SOFA_LIGHTS:
        s = slug(eid)
        cx, cy = cents[eid]
        raw_vars.append(
            '          raw_' + s + ': "{{ 1.0 if uniform else ' + E
            + ' ** (-1.0 * ((px - ' + str(cx) + ') ** 2 + (py - '
            + str(cy) + ') ** 2) / (lam * lam)) }}"')
        pct_vars.append(
            '          pct_' + s + ': "{{ (base * ([flr, raw_' + s
            + ' / (mx if mx > 0 else 1.0)] | max)) | round(0) | int }}"')
        attributes.append(
            '          ' + s + '_pct: "{{ pct_' + s + ' }}"')
        actuator.append('      - action: light.turn_on')
        actuator.append('        target:')
        actuator.append('          entity_id: ' + eid)
        actuator.append('        data:')
        actuator.append(
            "          brightness_pct: \"{{ [ state_attr("
            "'sensor.living_room_sofa_gradient', '" + s
            + "_pct') | int(5), 5 ] | max }}\"")
        actuator.append('          color_temp_kelvin: "{{ grad_ct }}"')
        actuator.append('          transition: 0.8')

    raw_list = ", ".join("raw_" + slug(e) for e in SOFA_LIGHTS)
    lights_dict = "{" + ", ".join(
        "'" + slug(e) + "': state_attr('sensor.living_room_sofa_gradient', '"
        + slug(e) + "_pct') | int(0)" for e in SOFA_LIGHTS) + "}"
    centroid_comment = "\n".join(
        "#   " + e + ": " + str(cents[e]) for e in SOFA_LIGHTS)

    return (_TEMPLATE
            .replace("@@CENTROID_COMMENT@@", centroid_comment)
            .replace("@@DW@@", str(dw))
            .replace("@@DH@@", str(dh))
            .replace("@@RAW_VARS@@", "\n".join(raw_vars))
            .replace("@@RAW_LIST@@", raw_list)
            .replace("@@PCT_VARS@@", "\n".join(pct_vars))
            .replace("@@ATTRIBUTES@@", "\n".join(attributes))
            .replace("@@ACTUATOR_ACTIONS@@", "\n".join(actuator))
            .replace("@@LIGHTS_DICT@@", lights_dict))


def main():
    cents, dw, dh = load_centroids()
    sep = GL.min_centroid_separation(cents)
    print("sofa light footprint centroids:")
    for eid in SOFA_LIGHTS:
        print(f"  {eid}: {cents[eid]}")
    print(f"min pairwise separation: {sep:.3f}")
    if sep is not None and sep < GL.MIN_SEPARATION_WARN:
        print(f"  WARNING [AR-3]: centroids closer than "
              f"{GL.MIN_SEPARATION_WARN} — the gradient would mostly amplify "
              f"position noise. Consider redrawing these footprints more "
              f"distinctly.")
    yaml_text = build_yaml(cents, dw, dh)
    OUT.write_text(yaml_text, encoding="utf-8")
    print(f"wrote {OUT} ({len(yaml_text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
